-- migrate:up
create table dndclasses(
   id         int generated by default as identity primary key,
   parent_id  int references dndclasses(id),
   name       text
 );

insert into dndclasses values
(1,null,'Warrior'),
(2,null,'Wizard'),
(3,null,'Priest'),
(4,null,'Rogue'),
(5,1,'Fighter'),
(6,1,'Paladin'),
(7,1,'Ranger'),
(8,2,'Mage'),
(9,2,'Specialist wizard'),
(10,3,'Cleric'),
(11,3,'Druid'),
(12,3,'Priest of specific mythos'),
(13,4,'Thief'),
(14,4,'Bard'),
(15,1,'Assassin');


-- migrate:down
drop table dndclasses;