// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"database/sql"
)

type Account struct {
	AccountID int32 `json:"account_id"`
	Balance   int32 `json:"balance"`
}

type Dndclass struct {
	ID       int32          `json:"id"`
	ParentID sql.NullInt32  `json:"parent_id"`
	Name     sql.NullString `json:"name"`
}
