version: '2'

services:
  db:
    image: postgres
    container_name: local-postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: my-secret-pw
      POSTGRES_DB: mydb